import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { Box, ChakraProvider, VStack } from "@chakra-ui/react";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body style={{ minHeight: "100vh", overflow: "hidden" }}>
        <Provider>
          <Box width="100%" minHeight="full" bg={"#f7f7f7"}>
            {children}
            <Toaster />
          </Box>
        </Provider>
      </body>
    </html>
  );
}
